// <auto-generated />
namespace CocktionMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class FillTheLocation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FillTheLocation));
        
        string IMigrationMetadata.Id
        {
            get { return "201502221733018_FillTheLocation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
