// <auto-generated />
namespace CocktionMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class _2fieldsDeletedFromProduct : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2fieldsDeletedFromProduct));
        
        string IMigrationMetadata.Id
        {
            get { return "201504111912325_2fieldsDeletedFromProduct"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
